[package]
name = "Learn_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rand = "0.9.1"
tokio ={version= "1.17",features=["full"]}
reqwest= {version="0.11",features=["json"]}
serde_json = "1.0"
serde= {version="1.0",features=["derive"]}
colored_json="2.0"
